# Generated by Django 3.0.4 on 2020-04-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_namivae',
            new_name='last_name',
        ),
    ]
